name: Build on release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install JDK
        uses: actions/setup-java@v4.7.0
      - name: Install Gradle
        uses: gradle/actions/setup-gradle@v4.3.1
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: ./gradlew distZip
      - name: Add build to release
        run: |
          cd ${{github.workspace}}
          gh release upload ${{github.event.release.tag_name}} build/distributions/ZomboidDecompiler.zip
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}