name: Build on release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install JDK
        uses: actions/setup-java@v4.7.0
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Install Gradle
        uses: gradle/actions/setup-gradle@v4.3.1

      - name: Checkout ZomboidDecompiler
        uses: actions/checkout@v5

      - name: Checkout Rosetta source
        uses: actions/checkout@v5
        with:
          repository: "PZ-Umbrella/pz-rosetta-source"
          path: "pz-rosetta-source"

      - name: Move Java Rosetta files
        run: |
          mkdir --parents src/main/resources
          mv pz-rosetta-source/rosetta/java src/main/resources/rosetta

      - name: Build
        run:
          ./gradlew distZip

      - name: Add build to release
        run:
          gh release upload ${{github.event.release.tag_name}} build/distributions/ZomboidDecompiler.zip
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
